// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotionPark.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MotionPark.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MotionParkDbContext))]
    partial class MotionParkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MotionPark.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime?>("CheckedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_in_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_booking");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_booking_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_booking_schedule_id");

                    b.HasIndex("CustomerId", "ScheduleId")
                        .HasDatabaseName("ix_booking_customer_id_schedule_id");

                    b.ToTable("booking", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Bookings.WaitingListEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_waiting_list_entry");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_waiting_list_entry_customer_id");

                    b.HasIndex("ScheduleId", "Status", "Position")
                        .HasDatabaseName("ix_waiting_list_entry_schedule_id_status_position");

                    b.ToTable("waiting_list_entry", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Catalog.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text")
                        .HasColumnName("description_en");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_activity");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_activity_category_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_activity_slug");

                    b.ToTable("activity", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Catalog.ActivityCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_activity_category");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_activity_category_slug");

                    b.ToTable("activity_category", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Catalog.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("OperatingHours")
                        .HasColumnType("jsonb")
                        .HasColumnName("operating_hours");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Whatsapp")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id")
                        .HasName("pk_branch");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_branch_slug");

                    b.ToTable("branch", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Catalog.ClassSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<int?>("AgeMax")
                        .HasColumnType("integer")
                        .HasColumnName("age_max");

                    b.Property<int?>("AgeMin")
                        .HasColumnType("integer")
                        .HasColumnName("age_min");

                    b.Property<int>("BookedCount")
                        .HasColumnType("integer")
                        .HasColumnName("booked_count");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("cancelled");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<Guid?>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("coach_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("GenderScope")
                        .HasColumnType("integer")
                        .HasColumnName("gender_scope");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WaitingListCount")
                        .HasColumnType("integer")
                        .HasColumnName("waiting_list_count");

                    b.HasKey("Id")
                        .HasName("pk_class_schedule");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_class_schedule_activity_id");

                    b.HasIndex("CoachId")
                        .HasDatabaseName("ix_class_schedule_coach_id");

                    b.HasIndex("BranchId", "Date")
                        .HasDatabaseName("ix_class_schedule_branch_id_date");

                    b.ToTable("class_schedule", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Catalog.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("BioAr")
                        .HasColumnType("text")
                        .HasColumnName("bio_ar");

                    b.Property<string>("BioEn")
                        .HasColumnType("text")
                        .HasColumnName("bio_en");

                    b.Property<string>("Certifications")
                        .HasColumnType("jsonb")
                        .HasColumnName("certifications");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_coach");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_coach_slug");

                    b.ToTable("coach", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Catalog.CoachActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("coach_id");

                    b.HasKey("Id")
                        .HasName("pk_coach_activity");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_coach_activity_activity_id");

                    b.HasIndex("CoachId", "ActivityId")
                        .IsUnique()
                        .HasDatabaseName("ix_coach_activity_coach_id_activity_id");

                    b.ToTable("coach_activity", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Catalog.CoachBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("coach_id");

                    b.HasKey("Id")
                        .HasName("pk_coach_branch");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_coach_branch_branch_id");

                    b.HasIndex("CoachId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("ix_coach_branch_coach_id_branch_id");

                    b.ToTable("coach_branch", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Catalog.ScheduleMembershipPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MembershipPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_plan_id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.HasKey("Id")
                        .HasName("pk_schedule_membership_plan");

                    b.HasIndex("MembershipPlanId")
                        .HasDatabaseName("ix_schedule_membership_plan_membership_plan_id");

                    b.HasIndex("ScheduleId", "MembershipPlanId")
                        .IsUnique()
                        .HasDatabaseName("ix_schedule_membership_plan_schedule_id_membership_plan_id");

                    b.ToTable("schedule_membership_plan", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Cms.Banner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text")
                        .HasColumnName("link_url");

                    b.Property<Guid?>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("SubtitleAr")
                        .HasColumnType("text")
                        .HasColumnName("subtitle_ar");

                    b.Property<string>("SubtitleEn")
                        .HasColumnType("text")
                        .HasColumnName("subtitle_en");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ar");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_banner");

                    b.ToTable("banner", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Cms.Faq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("AnswerAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_ar");

                    b.Property<string>("AnswerEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_en");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("QuestionAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_ar");

                    b.Property<string>("QuestionEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_en");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_faq");

                    b.ToTable("faq", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Cms.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid?>("MembershipPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_plan_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OdooLeadId")
                        .HasColumnType("text")
                        .HasColumnName("odoo_lead_id");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UtmCampaign")
                        .HasColumnType("text")
                        .HasColumnName("utm_campaign");

                    b.Property<string>("UtmMedium")
                        .HasColumnType("text")
                        .HasColumnName("utm_medium");

                    b.Property<string>("UtmSource")
                        .HasColumnType("text")
                        .HasColumnName("utm_source");

                    b.HasKey("Id")
                        .HasName("pk_lead");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_lead_status");

                    b.ToTable("lead", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Cms.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltAr")
                        .HasColumnType("text")
                        .HasColumnName("alt_ar");

                    b.Property<string>("AltEn")
                        .HasColumnType("text")
                        .HasColumnName("alt_en");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_media_asset");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_media_asset_category");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_media_asset_title");

                    b.ToTable("media_asset", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Cms.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentAr")
                        .HasColumnType("text")
                        .HasColumnName("content_ar");

                    b.Property<string>("ContentEn")
                        .HasColumnType("text")
                        .HasColumnName("content_en");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("text")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoKeywords")
                        .HasColumnType("text")
                        .HasColumnName("seo_keywords");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("text")
                        .HasColumnName("seo_title");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ar");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_page");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_page_slug");

                    b.ToTable("page", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Cms.PageSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section_key");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ar");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_page_section");

                    b.HasIndex("SectionKey")
                        .IsUnique()
                        .HasDatabaseName("ix_page_section_section_key");

                    b.ToTable("page_section", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Cms.Testimonial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("RoleAr")
                        .HasColumnType("text")
                        .HasColumnName("role_ar");

                    b.Property<string>("RoleEn")
                        .HasColumnType("text")
                        .HasColumnName("role_en");

                    b.Property<string>("TextAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_ar");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_en");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_testimonial");

                    b.ToTable("testimonial", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OdooPartnerId")
                        .HasColumnType("text")
                        .HasColumnName("odoo_partner_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_customer_phone");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_customer_user_id");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Identity.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_token");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_token_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_token_user_id");

                    b.ToTable("password_reset_token", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_permission");

                    b.HasIndex("RoleId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_permission_role_id_key");

                    b.ToTable("permission", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_token_user_id");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_role_name");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preferred_language");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_user_normalized_email")
                        .HasFilter("normalized_email IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_user_phone");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_role_id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_role_user_id_role_id");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Integrations.IntegrationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<Guid?>("LocalId")
                        .HasColumnType("uuid")
                        .HasColumnName("local_id");

                    b.Property<string>("OdooId")
                        .HasColumnType("text")
                        .HasColumnName("odoo_id");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_integration_logs");

                    b.HasIndex("Entity", "Timestamp")
                        .HasDatabaseName("ix_integration_logs_entity_timestamp");

                    b.ToTable("integration_logs", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Integrations.OdooMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid")
                        .HasColumnName("local_id");

                    b.Property<string>("OdooId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("odoo_id");

                    b.Property<string>("OdooModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("odoo_model");

                    b.HasKey("Id")
                        .HasName("pk_odoo_mapping");

                    b.HasIndex("EntityType", "LocalId")
                        .IsUnique()
                        .HasDatabaseName("ix_odoo_mapping_entity_type_local_id");

                    b.ToTable("odoo_mapping", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Integrations.OdooSyncJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("JobType")
                        .HasColumnType("integer")
                        .HasColumnName("job_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("MotionParkTransactionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motion_park_transaction_id");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_odoo_sync_job");

                    b.HasIndex("MotionParkTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_odoo_sync_job_motion_park_transaction_id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_odoo_sync_job_status_next_attempt_at");

                    b.ToTable("odoo_sync_job", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Membership.CustomerMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_renew");

                    b.Property<int>("BillingCycle")
                        .HasColumnType("integer")
                        .HasColumnName("billing_cycle");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid>("MembershipPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_plan_id");

                    b.Property<DateTime?>("NextBillingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_billing_date");

                    b.Property<string>("OdooSubscriptionId")
                        .HasColumnType("text")
                        .HasColumnName("odoo_subscription_id");

                    b.Property<string>("OdooSyncJobTransactionId")
                        .HasColumnType("text")
                        .HasColumnName("odoo_sync_job_transaction_id");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("payment_status");

                    b.Property<string>("QrTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("qr_token_hash");

                    b.Property<DateTime?>("QrTokenRotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("qr_token_rotated_at");

                    b.Property<int?>("RemainingSessions")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_sessions");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customer_membership");

                    b.HasIndex("MembershipPlanId")
                        .HasDatabaseName("ix_customer_membership_membership_plan_id");

                    b.HasIndex("OdooSyncJobTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_membership_odoo_sync_job_transaction_id")
                        .HasFilter("odoo_sync_job_transaction_id IS NOT NULL");

                    b.HasIndex("CustomerId", "Status")
                        .HasDatabaseName("ix_customer_membership_customer_id_status");

                    b.ToTable("customer_membership", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Membership.MembershipPlanReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Activities")
                        .HasColumnType("jsonb")
                        .HasColumnName("activities");

                    b.Property<string>("Branches")
                        .HasColumnType("jsonb")
                        .HasColumnName("branches");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text")
                        .HasColumnName("description_en");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<string>("DurationUnit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("duration_unit");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean")
                        .HasColumnName("featured");

                    b.Property<string>("FeaturesAr")
                        .HasColumnType("jsonb")
                        .HasColumnName("features_ar");

                    b.Property<string>("FeaturesEn")
                        .HasColumnType("jsonb")
                        .HasColumnName("features_en");

                    b.Property<bool>("IsConfigurablePlaceholder")
                        .HasColumnType("boolean")
                        .HasColumnName("is_configurable_placeholder");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<int?>("OdooProductId")
                        .HasColumnType("integer")
                        .HasColumnName("odoo_product_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("SessionLimit")
                        .HasColumnType("integer")
                        .HasColumnName("session_limit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Vat")
                        .HasColumnType("numeric")
                        .HasColumnName("vat");

                    b.HasKey("Id")
                        .HasName("pk_membership_plan_read_models");

                    b.HasIndex("OdooProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_membership_plan_read_models_odoo_product_id")
                        .HasFilter("odoo_product_id IS NOT NULL");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_membership_plan_read_models_slug");

                    b.ToTable("membership_plan_read_models", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("CustomerMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_membership_id");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("OdooInvoiceId")
                        .HasColumnType("text")
                        .HasColumnName("odoo_invoice_id");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Vat")
                        .HasColumnType("numeric")
                        .HasColumnName("vat");

                    b.HasKey("Id")
                        .HasName("pk_payment");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_payment_customer_id");

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Payments.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("FailureCode")
                        .HasColumnType("text")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("text")
                        .HasColumnName("failure_message");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderReference")
                        .HasColumnType("text")
                        .HasColumnName("provider_reference");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payment_transaction");

                    b.HasIndex("IdempotencyKey")
                        .HasDatabaseName("ix_payment_transaction_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.ToTable("payment_transaction", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Settings.BrandSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("colors");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact");

                    b.Property<string>("FaviconUrl")
                        .HasColumnType("text")
                        .HasColumnName("favicon_url");

                    b.Property<string>("Gradients")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gradients");

                    b.Property<string>("LogoDarkUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_dark_url");

                    b.Property<string>("LogoLightUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_light_url");

                    b.Property<string>("LogoPrimaryUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_primary_url");

                    b.Property<string>("SocialLinks")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("social_links");

                    b.Property<string>("Typography")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("typography");

                    b.HasKey("Id")
                        .HasName("pk_brand_settings");

                    b.ToTable("brand_settings", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Settings.SystemSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_language");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("features");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("languages");

                    b.Property<bool>("MaintenanceMode")
                        .HasColumnType("boolean")
                        .HasColumnName("maintenance_mode");

                    b.Property<bool>("RegistrationOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("registration_open");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.HasKey("Id")
                        .HasName("pk_system_settings");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.System.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorName")
                        .HasColumnType("text")
                        .HasColumnName("actor_name");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Changes")
                        .HasColumnType("text")
                        .HasColumnName("changes");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("Entity", "EntityId")
                        .HasDatabaseName("ix_audit_log_entity_entity_id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.System.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyAr")
                        .HasColumnType("text")
                        .HasColumnName("body_ar");

                    b.Property<string>("BodyEn")
                        .HasColumnType("text")
                        .HasColumnName("body_en");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ar");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_notification_user_id_status");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("MotionPark.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("MotionPark.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_customer_customer_id");

                    b.HasOne("MotionPark.Domain.Catalog.ClassSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_class_schedule_schedule_id");

                    b.Navigation("Customer");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("MotionPark.Domain.Bookings.WaitingListEntry", b =>
                {
                    b.HasOne("MotionPark.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_waiting_list_entry_customer_customer_id");

                    b.HasOne("MotionPark.Domain.Catalog.ClassSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_waiting_list_entry_class_schedule_schedule_id");

                    b.Navigation("Customer");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("MotionPark.Domain.Catalog.Activity", b =>
                {
                    b.HasOne("MotionPark.Domain.Catalog.ActivityCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_activity_activity_category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MotionPark.Domain.Catalog.ClassSchedule", b =>
                {
                    b.HasOne("MotionPark.Domain.Catalog.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_schedule_activity_activity_id");

                    b.HasOne("MotionPark.Domain.Catalog.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_schedule_branch_branch_id");

                    b.HasOne("MotionPark.Domain.Catalog.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .HasConstraintName("fk_class_schedule_coach_coach_id");

                    b.Navigation("Activity");

                    b.Navigation("Branch");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("MotionPark.Domain.Catalog.CoachActivity", b =>
                {
                    b.HasOne("MotionPark.Domain.Catalog.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coach_activity_activity_activity_id");

                    b.HasOne("MotionPark.Domain.Catalog.Coach", "Coach")
                        .WithMany("CoachActivities")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coach_activity_coach_coach_id");

                    b.Navigation("Activity");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("MotionPark.Domain.Catalog.CoachBranch", b =>
                {
                    b.HasOne("MotionPark.Domain.Catalog.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coach_branch_branch_branch_id");

                    b.HasOne("MotionPark.Domain.Catalog.Coach", "Coach")
                        .WithMany("CoachBranches")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coach_branch_coach_coach_id");

                    b.Navigation("Branch");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("MotionPark.Domain.Catalog.ScheduleMembershipPlan", b =>
                {
                    b.HasOne("MotionPark.Domain.Membership.MembershipPlanReadModel", "MembershipPlan")
                        .WithMany()
                        .HasForeignKey("MembershipPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_membership_plan_membership_plan_read_model_members");

                    b.HasOne("MotionPark.Domain.Catalog.ClassSchedule", "Schedule")
                        .WithMany("SchedulePlans")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_membership_plan_class_schedule_schedule_id");

                    b.Navigation("MembershipPlan");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("MotionPark.Domain.Customers.Customer", b =>
                {
                    b.HasOne("MotionPark.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_customer_user_user_id");
                });

            modelBuilder.Entity("MotionPark.Domain.Identity.PasswordResetToken", b =>
                {
                    b.HasOne("MotionPark.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_token_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotionPark.Domain.Identity.Permission", b =>
                {
                    b.HasOne("MotionPark.Domain.Identity.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permission_role_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MotionPark.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("MotionPark.Domain.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotionPark.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("MotionPark.Domain.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_role_id");

                    b.HasOne("MotionPark.Domain.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_user_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotionPark.Domain.Membership.CustomerMembership", b =>
                {
                    b.HasOne("MotionPark.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_membership_customer_customer_id");

                    b.HasOne("MotionPark.Domain.Membership.MembershipPlanReadModel", "MembershipPlan")
                        .WithMany()
                        .HasForeignKey("MembershipPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_membership_membership_plan_read_model_membership_p");

                    b.Navigation("Customer");

                    b.Navigation("MembershipPlan");
                });

            modelBuilder.Entity("MotionPark.Domain.Payments.Payment", b =>
                {
                    b.HasOne("MotionPark.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_customer_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MotionPark.Domain.Catalog.ClassSchedule", b =>
                {
                    b.Navigation("SchedulePlans");
                });

            modelBuilder.Entity("MotionPark.Domain.Catalog.Coach", b =>
                {
                    b.Navigation("CoachActivities");

                    b.Navigation("CoachBranches");
                });

            modelBuilder.Entity("MotionPark.Domain.Identity.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MotionPark.Domain.Identity.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
